include:
  - board: xiao_ble
    shield: fuji44_dongle
    artifact-name: fuji44_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: fuji44_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: fuji44_left
  - board: nice_nano
    shield: fuji44_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: fuji44_right
  - board: nice_nano
    shield: settings_reset
    artifact-name: fuji44_settings_reset
  - board: xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
